### ISSUE TITLE
Fav's "Add New Group" Command/Icon and Context Menu Entries Show Up in the Side Bar View of Other Extensions

### ISSUE THREAD

**Issue by SolarTheory** [fredjeck/fav#17] opened 2021-01-18 08:08 UTC
Hopefully I can explain this:  Fav has a command to "Add New Group" that is represented by a folder icon in the title area of the extension's View module in the Side Bar.  The problem is that this icon and associated command bleeds into and shows up in the 'Views' (i.e. the Explorer Side Bar modules) of other extensions.  Since the icon/command is associated with Fav, click on it creates a new group in the Fav extension, even when Fav is not in focus.  

Similarly, when focus is on the View of another extension in the Side Bar and I right-click on a file or other entry for that extension, the context menu includes Fav's commands (Move to..., Remove, Rename). This can be quite confusing when you are expecting to invoke a command associated with the extension that in focus.  I accidently deleted a bunch of Fav favorites before I figured out why my favorite groups kept getting deleted. 

Hopefully the above makes sense.

**Comment by fredjeck** [comment] 2021-01-18 12:31
I think I found the problem's source, I am however not able to reproduce it locally.
May I ask you in which extension Fav's menus are bleeding ?

**Comment by SolarTheory** [comment] 2021-01-18 16:09
It happens with all 3rd-party extensions as far as I can tell. As an example, I see it bleeding into these extensions I have enabled: "Task Explorer", "easy-snippet", "PowerShell" (in the Powershell Command Explorer), "Tab Groups", "Workspace Sidebar", "Favorites Panel", etc..  It's not happening with built-in Explorer Views, with the following exception:  I can see the "Add new group" icon/command in the Folders Explorer View before a folder is opened. After a folder is opened, the icon becomes associated with creating a "New Folder".

I am surprised that you can't repro it.  I just did a clean install of VS Code in a fresh Windows installation and I immediately see the bleeding of the "Add new group" in the Folder Explorer View.  Upon installing a 3rd-party extension (Task Explorer), I see the bleed of the context menus and the "Add new group" there are well.

**Comment by fredjeck** [comment] 2021-01-18 17:46
The environment I'm using to develop the extension is pretty light on extensions that's why I was not able to reproduce it.
Thanks for the additional input

**Comment by fredjeck** [comment] 2021-01-18 18:03
Thanks for submitting and adding extra info. The issue should now be fixed with release 1.5.3 which I just published.

**Closed as completed by fredjeck** 2021-01-18 18:03 UTC
Labels: bug

**Comment by SolarTheory** [comment] 2021-01-19 01:04
Thank you for a wonderful extension! Hopefully it gets more DLs and reviews.  It has a lot of potential.  I will make some suggestions for improvement.
